### ISSUE TITLE
有两个建议

### ISSUE THREAD

**Issue by ghost** [jhuix/showdowns#1]
这个编辑器太强悍了，但是有两点建议：不知道能集成markdown-it插件吗，如果可以的话，要是集成markdown-it-container和markdown-it-table就好了

markdown-it-container可以定义:::info :::、:::success :::、:::error ::: 标签
markdown-it-table可以快捷操作table

**Comment by jhuix** [comment]
实际上showdown.js和markdown-it是两种完全不同的markdown文本解析器，直接集成markdown-it插件不可行；
为了实现你说的两种效果(markdown-it-container和markdown-it-table所实现的效果)，理论上有两种方法：
一种是使用原生showdown解析器生成上述效果的插件；另一种是生成可嵌入使用markdown-it解析器及集成markdown-it插件来解析出的HTML的showdown插件。

**Comment by ghost** [comment]
我起初没仔细看，还以为编辑器是用markdown-it渲染的，没想到是使用markdown.js，正如你所说，showdown.js和markdown-it是两种完全不同的markdown文本解析器，我看了绝大多数markdown编辑器都是使用的markdown-it作为渲染的，我感觉其中很重要一点就是markdown-it易扩展，所以生态好，所以如果你打算更多的人使用这个插件，还是改成markdown-it的好。

**Comment by jhuix** [comment]
> 我起初没仔细看，还以为编辑器是用markdown-it渲染的，没想到是使用markdown.js，正如你所说，showdown.js和markdown-it是两种完全不同的markdown文本解析器，我看了绝大多数markdown编辑器都是使用的markdown-it作为渲染的，我感觉其中很重要一点就是markdown-it易扩展，所以生态好，所以如果你打算更多的人使用这个插件，还是改成markdown-it的好。

这是仁者见仁，各有各的爱好 :-)

**Comment by jhuix** [comment]
版本0.5.0开始已实现showdown-container可以达到markdown-it-container插件的效果了，table语法也演化实现了表格中向左或向上合并单元格效果。

**Comment by jhuix** [comment]
> > 我起初没仔细看，还以为编辑器是用markdown-it渲染的，没想到是使用markdown.js，正如你所说，showdown.js和markdown-it是两种完全不同的markdown文本解析器，我看了绝大多数markdown编辑器都是使用的markdown-it作为渲染的，我感觉其中很重要一点就是markdown-it易扩展，所以生态好，所以如果你打算更多的人使用这个插件，还是改成markdown-it的好。
> 
> 这是仁者见仁，各有各的爱好 :-)

版本0.5.0开始已实现showdown-container可以达到markdown-it-container插件的效果了，table语法也演化实现了表格中向左或向上合并单元格效果。
