### ISSUE TITLE
Image link error

### ISSUE THREAD

**Issue by NigelWGMajor** [jhuix/showdowns#2]
Image links work great when the link is to a url, but links to local files do not render.
T
hey do in the "ordinary" markdown previewer, but not in this one, which is a great pity because this is otherwise AWESOME.

`![test](./../media/20200812_153806.jpg "Test Image")`

should show a local image...

**Comment by jhuix** [comment]
> Image links work great when the link is to a url, but links to local files do not render. T hey do in the "ordinary" markdown previewer, but not in this one, which is a great pity because this is otherwise AWESOME.
> 
> `![test](./../media/20200812_153806.jpg "Test Image")`
> 
> should show a local image...

It will be parsed as image element of HTML, and the link address will be assigned to the src item of image element. However, the HTML specification specifies that when src is represented as a relative path, it refers to the relative path of the requested page URL. Therefore, it is not necessarily mandatory to use a local path.
